### ISSUE TITLE
Separate ES-related infrastructure code from application code

### ISSUE THREAD

**Issue by tjuerge** [eugene-khyst/postgresql-event-sourcing#8]
Currently the application code is entangled with the generic ES-related infrastructure code, e.g. the enums `EventType` and `AggregateType` are pulling-in domain-specific code into the generic `EventRegistry`and `AggregateRegistry` implementations. 

For a simple example this is ok, but for a template of a production-grade application this could be improved - maybe by aligning to the architecture approach of Clean Architecture (as Tom Hombergs describes it in his blog post [Hexagonal Architecture with Java and Spring](https://reflectoring.io/spring-hexagonal/) and his book [Get Your Hands Dirty on Clean Architecture ](https://reflectoring.io/book/)).

So I would like to suggest refactoring the ES-related infrastructure code from the application into it's own package or module.

**Comment by cloudcompute** [comment]
Hi, Documentation is great. Is the code production-grade/ready?

**Comment by eugene-khyst** [comment]
Yes, the code is production-grade. For simplicity, there is only one Gradle module. In the real applications it may have sense to extract the event sourcing infrastructure code to the separate Gradle module or even project.
I plan to implement it soon. But it is more about project directory structure.

**Comment by cloudcompute** [comment]
Thanks for the response.

`event sourcing infrastructure code`
You want to say that the `generic code` relating to event-sourcing should be placed in a separate directory, am I right? The main directories are config, repository and service.

The code placed in the `projections directory` is domain-specific. Why have you decided not to make it generic. Is it because the projection could be any.. just like we can write different types of Queries for a given domain/microservice.. extraction of the generic projection does not make sense?

**Comment by eugene-khyst** [comment]
For the event sourcing part there are quite a lot of generic code that can be reused by multiple domains if extracted into a separate Gradle module. Of course, there are also domain-specific code for event sourcing part (the concrete commands, events event handlers).
Projections doesn't require any generic code because they completely rely on Spring Data JPA. All we need for projections are Spring Data JPA repositories and JPA entities.

Source code files will be split between Gradle modules the following way:

## Infrastructure code (generic code)

- com/example/eventsourcing/config/
  - [EventSourcingProperties](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/config/EventSourcingProperties.java)

- com/example/eventsourcing/domain/
  - [Aggregate](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/Aggregate.java)

- com/example/eventsourcing/domain/command/
  - [Command](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/command/Command.java)

- com/example/eventsourcing/domain/event/
  - [Event](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/Event.java)
  - [EventSubscriptionCheckpoint](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/EventSubscriptionCheckpoint.java)
  - [EventWithId](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/EventWithId.java)

- com/example/eventsourcing/repository/
  - [AggregateRepository](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/repository/AggregateRepository.java)
  - [EventRepository](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/repository/EventRepository.java)
  - [EventSubscriptionRepository](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/repository/EventSubscriptionRepository.java)

- com/example/eventsourcing/service/
  - [AggregateStore](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/AggregateStore.java)
  - [CommandProcessor](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/CommandProcessor.java)
  - [EventSubscriptionProcessor](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/EventSubscriptionProcessor.java)
  - [PostgresChannelEventSubscriptionProcessor](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/PostgresChannelEventSubscriptionProcessor.java)
  - [ScheduledEventSubscriptionProcessor](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/ScheduledEventSubscriptionProcessor.java)

- com/example/eventsourcing/service/command/
  - [CommandHandler](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/command/CommandHandler.java)
  - [DefaultCommandHandler](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/command/DefaultCommandHandler.java)

- com/example/eventsourcing/service/event/
  - [SyncEventHandler](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/event/SyncEventHandler.java)
  - [AsyncEventHandler](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/event/AsyncEventHandler.java)

- com/example/eventsourcing/error/
  - [Error](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/error/Error.java)
  - [OptimisticConcurrencyControlError](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/error/OptimisticConcurrencyControlError.java)

## Application code (domain-specific code)

com/example/eventsourcing/config/
  - [KafkaTopicsConfig](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/config/KafkaTopicsConfig.java)

- com/example/eventsourcing/domain/
  - [AggregateType](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/AggregateType.java)
  - [OrderAggregate](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/OrderAggregate.java)

- com/example/eventsourcing/domain/command/
  - [AcceptOrderCommand](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/command/AcceptOrderCommand.java)
  - [AdjustOrderPriceCommand](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/command/AdjustOrderPriceCommand.java)
  - [CancelOrderCommand](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/command/CancelOrderCommand.java)
  - [CompleteOrderCommand](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/command/CompleteOrderCommand.java)
  - [PlaceOrderCommand](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/command/PlaceOrderCommand.java)

- com/example/eventsourcing/domain/event/
  - [EventType](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/EventType.java)
  - [OrderAcceptedEvent](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/OrderAcceptedEvent.java)
  - [OrderCancelledEvent](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/OrderCancelledEvent.java)
  - [OrderCompletedEvent](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/OrderCompletedEvent.java)
  - [OrderPlacedEvent](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/OrderPlacedEvent.java)
  - [OrderPriceAdjustedEvent](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/domain/event/OrderPriceAdjustedEvent.java)

- com/example/eventsourcing/projection/
  - [OrderProjection](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/projection/OrderProjection.java)
  - [WaypointProjection](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/projection/WaypointProjection.java)

- com/example/eventsourcing/repository/
  - [OrderProjectionRepository](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/repository/OrderProjectionRepository.java)

- com/example/eventsourcing/service/command/
  - [PlaceOrderCommandHandler](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/command/PlaceOrderCommandHandler.java)

- com/example/eventsourcing/service/event/
  - [OrderProjectionUpdater](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/event/OrderProjectionUpdater.java)
  - [OrderIntegrationEventSender](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/service/event/OrderIntegrationEventSender.java)

- com/example/eventsourcing/dto/
  - [OrderDto](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/dto/OrderDto.java)
  - [OrderStatus](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/dto/OrderStatus.java)
  - [WaypointDto](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/dto/WaypointDto.java)

- com/example/eventsourcing/mapper/
  - [OrderMapper](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/mapper/OrderMapper.java)

- com/example/eventsourcing/controller/
  - [OrdersController](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/controller/OrdersController.java)
  - [RestResponseEntityExceptionHandler](https://github.com/eugene-khyst/postgresql-event-sourcing/blob/main/src/main/java/com/example/eventsourcing/controller/RestResponseEntityExceptionHandler.java)

@tjuerge , what do you think about splitting the code the way I described?

**Comment by cloudcompute** [comment]
Great.. and thanks

**Comment by tjuerge** [comment]
> what do you think about splitting the code the way I described?

I'm leaning more towards the coarse-grained structure of Eventuous (C# based ES implementation) https://eventuous.dev/docs/prologue/the-right-way/
<img width="453" alt="image" src="https://github.com/eugene-khyst/postgresql-event-sourcing/assets/2626998/fa9d0ec0-0233-4cfa-95dd-0800d9afea4e">
* Core -> generic API and technology agnostic implementation, no frameworks like Spring or any other infrastructure code
  * Domain
  * Persistence
  * Application
* Infrastructure -> technology-specific implementation, like Spring and Postgres
  * Postgres
